# Define the default target
ALL: wordle

# Find all source files and header files
SOURCES := $(wildcard *.cpp)
HEADERS := $(wildcard *.h)

OBJECTS := $(SOURCES:.cpp=.o)

%.o : %.cpp ${HEADERS}
	g++ -c $
